### PR TITLE
Improve MacOS support via CrossOver

### PR DESCRIPTION
**Pull request by JxxIT**
Improve https://github.com/BeamMP/BeamMP-Launcher/pull/147

### CODE REVIEW

**Comment by JxxIT** [comment]
@enzofrnt Please test this before merging, it works for me, but maybe it doesn't for you.

**Comment by enzofrnt** [comment]
could you please explain what you have done, to have a resume.
Thanks

**Comment by JxxIT** [comment]
I've removed the folder scanning. CrossOver stores its paths and makes it avaliable trough a shell command. It runs the command to automatically gets the bottles folder and the wine path.

**Comment by enzofrnt** [comment]
ok I will take a look, can you verify that you are up to date with my last modification ?

**Comment by JxxIT** [comment]
Commit https://github.com/BeamMP/BeamMP-Launcher/pull/147/commits/99d3a79038e0d7a7bd1872019e10f5cceeb23955?

**Comment by enzofrnt** [comment]
yes

**Comment by JxxIT** [comment]
Yeah I am. I see the linux build failed tho, I'll try to fix it.

**Comment by enzofrnt** [comment]
Are you available on discord ?

**Comment by JxxIT** [comment]
Yeah I am, my username is `jxxit_`

**Pull request merged**
